python main.py \
    --output_dir=./saved_models \
    --model_name=model.bin \
    --tokenizer_name=microsoft/graphcodebert-base \
    --model_name_or_path=microsoft/graphcodebert-base \
    --train_data_file=../../data/bigvul/train.json \
    --eval_data_file=../../data/bigvul/val.json \
    --test_data_file=../../data/bigvul/test.json \
    --dataset=json \
    --data_type=vul \
    --do_train \
    --block_size 512 \
    --epochs 10 \
    --train_batch_size 128 \
    --eval_batch_size 128 \
    --learning_rate 2e-3 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --hidden_size 256 \
    --early_stopping_patience 5 \
    --seed 123456  2>&1 | tee train.log