python student_codebert_main.py \
    --alpha 0.7 \
    --output_dir=./saved_models \
    --model_name=soft_distil_model_megavul.bin \
    --tokenizer_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --train_data_file=../../data/megavul/train.json \
    --eval_data_file=../../data/megavul/val.json \
    --test_data_file=../../data/megavul/test.json \
    --dataset=json \
    --do_train \
    --do_test \
    --block_size 512 \
    --epochs 20 \
    --train_batch_size 16 \
    --eval_batch_size 16 \
    --learning_rate 2e-4 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456  2>&1 | tee train_soft_distil_alpha07.log